services:
  roko.template-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: roko.template-mssql
    volumes:
      - c:/data:/var/opt/mssql/data
      - c:/log:/var/opt/mssql/log
      - c:/secrets:/var/opt/mssql/secrets
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: yourStrong(!)Password
      MSSQL_PID: Developer
    restart: unless-stopped
    ports:
      - "1433:1433"
